sudo: required
dist: trusty

language: python

python:
  - 2.7
  - 3.5

matrix:
  exclude:
    - python: 2.7
    - python: 3.5
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.5
      env: TOX_ENV=py35

cache:
  directories:
    - $HOME/.cache/pip

install: pip install -r requirements.txt

script: tox -epep8,${TOX_ENV}

notifications:
  email: false
