sudo: required

services:
  - docker

language: python
python:
  - 3.5

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt

script:
  - tox

notifications:
  email: false
